<?php

/**
 * @file
 * Contains service_club_asset.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\service_club_asset\Entity\AssetEntity;

/**
 * Implements hook_help().
 */
function service_club_asset_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the service_club_asset module.
    case 'help.page.service_club_asset':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module provides functionality to manage assets in an organisation. From associations to asset expiry this module will give event organisers the ability to effectively manage assets at events.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Cron job for Asset Entities checking if it has expired.
 */
function service_club_asset_cron() {
  // Load all the assets into an array.
  $assets = AssetEntity::loadMultiple();

  // Create a queue to load the assets into for the next cron run.
  $queue = \Drupal::queue('asset_entity_processor');

  // Check the asset has an expiry.
  foreach ($assets as $asset) {
    // No date is recognised as empty so if it isn't empty queue the asset.
    if (!empty($asset->getExpiryDate())) {
      $queue->createItem($asset);
    }
  }
}

/**
 * Implements hook_theme().
 */
function service_club_asset_theme() {
  return [
    'service_club_asset' => [
      'render element' => 'children',
    ],
    'asset_entity' => [
      'template' => 'asset_entity',
      'render element' => 'content',
    ],
  ];
}
